//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeCarros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veiculos()
        {
            this.Gastos = new HashSet<Gastos>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Modelo { get; set; }
        public int AnoFab { get; set; }
        public int AnoMod { get; set; }
        public string Motor { get; set; }
        public string Cor { get; set; }
        public double ValorPago { get; set; }
        public bool Financiado { get; set; }
        public int CategoriasId { get; set; }
        public int MarcasId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gastos> Gastos { get; set; }
        public virtual Categorias Categorias { get; set; }
        public virtual Marcas Marcas { get; set; }
    }
}
